const ROUTE_KEYS = {
    FRONTPAGE: "FRONTPAGE",
    LIST_ORDERS: "LIST_ORDERS",
    CREATE_ORDER: "CREATE_ORDER",
    MANAGE_ORDER: "MANAGE_ORDER",
    LIST_PRODUCTS: "LIST_PRODUCTS",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    LIST_PRODUCT_HISTORIES: "LIST_PRODUCT_HISTORIES",
    LOADER_ERROR: "LOADER_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    CLIENT_SIDE_ERROR: "CLIENT_SIDE_ERROR"
} as const;

export default ROUTE_KEYS;