stages:
    - deploy

deploy:
    stage: deploy
    script:
        - mkdir -p ~/.ssh
        
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_gitlab
        - chmod 600 ~/.ssh/id_rsa_gitlab

        - ssh -i ~/.ssh/id_rsa_gitlab root@$HETZNER_IPV4 "
            cd /root/Dotnet-React-Order-Display-System || mkdir -p /root/Dotnet-React-Order-Display-System && cd /root/Dotnet-React-Order-Display-System;
            if [ ! -d .git ]; then
              git clone git@gitlab.com:username/repository.git .;
            else
              git reset --hard;
              git pull origin master;
            fi
            echo 'VITE_API_URL=http://${HETZNER_IPV4}:5000' > frontend/.env.production;
            docker-compose up
          "
    only:
        - master
