stages:
  - deploy

deploy:
  stage: deploy
  image: ruby:3.1
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $HETZNER_IPV4 >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_gitlab
    - chmod 600 ~/.ssh/id_rsa_gitlab
    
    # SSH command to interact with the server
    - ssh -i ~/.ssh/id_rsa_gitlab root@$HETZNER_IPV4 "
        mkdir -p /root/app;
        cd /root/app;
        
        if [ -d .git ]; then
          echo 'Repository exists, pulling latest changes...';
          git fetch origin;
          git reset --hard origin/master;
        else
          echo 'Cloning repository...';
          rm -rf * .[^.]*;
          git clone git@gitlab.com:m-7ard/Dotnet-React-Order-Display-System.git .;
        fi;
        
        echo 'Folder structure after update:';
        ls -la;
        
        mkdir -p frontend;
        echo 'VITE_API_URL=http://${HETZNER_IPV4}:5000' > frontend/.env.production;
        
        docker-compose up -d;
      "
  only:
    - master