stages:
  - deploy

deploy:
  stage: deploy
  image: ruby:3.1
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $HETZNER_IPV4 >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_gitlab
    - chmod 600 ~/.ssh/id_rsa_gitlab
    
    # SSH command to interact with the server
    - ssh -i ~/.ssh/id_rsa_gitlab root@$HETZNER_IPV4 "
        mkdir -p /root/Dotnet-React-Order-Display-System;

        echo 'Folder structure after mkdir:';
        ls -l;

        cd /root/Dotnet-React-Order-Display-System;

        echo 'Folders after cd:';
        ls -l;
      "
  only:
    - master